import 'controller/live_chat_3_hosts_host_is_talking_one_controller.dart';import 'package:flutter/material.dart';import 'package:green_house/core/app_export.dart';import 'package:green_house/presentation/live_chat_3_hosts_host_is_talking_two_bottomsheet/live_chat_3_hosts_host_is_talking_two_bottomsheet.dart';import 'package:green_house/presentation/live_chat_3_hosts_host_is_talking_two_bottomsheet/controller/live_chat_3_hosts_host_is_talking_two_controller.dart';import 'package:green_house/presentation/live_chat_3_hosts_host_is_talking_five_bottomsheet/live_chat_3_hosts_host_is_talking_five_bottomsheet.dart';import 'package:green_house/presentation/live_chat_3_hosts_host_is_talking_five_bottomsheet/controller/live_chat_3_hosts_host_is_talking_five_controller.dart';
// ignore_for_file: must_be_immutable
class LiveChat3HostsHostIsTalkingOneBottomsheet extends StatelessWidget {LiveChat3HostsHostIsTalkingOneBottomsheet(this.controller);

LiveChat3HostsHostIsTalkingOneController controller;

@override Widget build(BuildContext context) { return SingleChildScrollView(child: Container(width: double.maxFinite, child: Container(width: double.maxFinite, padding: getPadding(left: 24, top: 10, right: 24, bottom: 10), decoration: AppDecoration.fillGray90001.copyWith(borderRadius: BorderRadiusStyle.customBorderTL24), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Container(height: getVerticalSize(4), width: getHorizontalSize(44), decoration: BoxDecoration(color: ColorConstant.green500, borderRadius: BorderRadius.circular(getHorizontalSize(2))))), GestureDetector(onTap: () {onTapTxtAudienceinterac();}, child: Padding(padding: getPadding(top: 31), child: Text("msg_audience_interaction".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsMedium14WhiteA700))), Padding(padding: getPadding(top: 23), child: Text("lbl_share".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsMedium14WhiteA700)), Padding(padding: getPadding(top: 25), child: Text("lbl_manage_co_host".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsMedium14WhiteA700)), Padding(padding: getPadding(top: 24), child: Text("lbl_view_rules".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsMedium14WhiteA700)), GestureDetector(onTap: () {onTapTxtSave();}, child: Padding(padding: getPadding(top: 27), child: Text("lbl_share_feedback".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsMedium14WhiteA700))), GestureDetector(onTap: () {onTapTxtDownload();}, child: Padding(padding: getPadding(top: 29, bottom: 81), child: Text("lbl_report".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsMedium14WhiteA700)))])))); } 
onTapTxtAudienceinterac() { Get.toNamed(AppRoutes.liveChat1HostsTwoScreen); } 
onTapTxtSave() { Get.bottomSheet(LiveChat3HostsHostIsTalkingTwoBottomsheet(Get.put(LiveChat3HostsHostIsTalkingTwoController(),),),isScrollControlled: true,); } 
onTapTxtDownload() { Get.bottomSheet(LiveChat3HostsHostIsTalkingFiveBottomsheet(Get.put(LiveChat3HostsHostIsTalkingFiveController(),),),isScrollControlled: true,); } 
 }
