import '../live_chat_3_hosts_host_is_talking_nine_bottomsheet/widgets/listrectangle46_item_widget.dart';import 'controller/live_chat_3_hosts_host_is_talking_nine_controller.dart';import 'models/listrectangle46_item_model.dart';import 'package:flutter/material.dart';import 'package:green_house/core/app_export.dart';import 'package:green_house/presentation/live_chat_3_hosts_host_is_talking_seven_bottomsheet/live_chat_3_hosts_host_is_talking_seven_bottomsheet.dart';import 'package:green_house/presentation/live_chat_3_hosts_host_is_talking_seven_bottomsheet/controller/live_chat_3_hosts_host_is_talking_seven_controller.dart';
// ignore_for_file: must_be_immutable
class LiveChat3HostsHostIsTalkingNineBottomsheet extends StatelessWidget {LiveChat3HostsHostIsTalkingNineBottomsheet(this.controller);

LiveChat3HostsHostIsTalkingNineController controller;

@override Widget build(BuildContext context) { return SingleChildScrollView(child: Container(width: double.maxFinite, child: Container(width: double.maxFinite, padding: getPadding(left: 8, top: 10, right: 8, bottom: 10), decoration: AppDecoration.fillGray90001.copyWith(borderRadius: BorderRadiusStyle.customBorderTL24), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Container(height: getVerticalSize(4), width: getHorizontalSize(44), decoration: BoxDecoration(color: ColorConstant.green500, borderRadius: BorderRadius.circular(getHorizontalSize(2))))), Padding(padding: getPadding(left: 8, top: 35), child: Row(children: [Text("lbl_group_chat".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsSemiBold18Gray600), Padding(padding: getPadding(left: 24), child: Text("lbl_direct_message".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsSemiBold18)), Spacer(), CustomImageView(svgPath: ImageConstant.imgCrosssmall1WhiteA700, height: getSize(24), width: getSize(24), margin: getMargin(bottom: 3))])), Align(alignment: Alignment.centerRight, child: SizedBox(width: getHorizontalSize(225), child: Divider(height: getVerticalSize(2), thickness: getVerticalSize(2), color: ColorConstant.whiteA700, endIndent: getHorizontalSize(76)))), Padding(padding: getPadding(left: 22, top: 16), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgWeed0116x16, height: getSize(16), width: getSize(16), margin: getMargin(top: 1)), Padding(padding: getPadding(left: 13), child: Text("lbl_500_members".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsRegular12))])), Padding(padding: getPadding(left: 8, top: 15, right: 8, bottom: 56), child: Obx(() => ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: getVerticalSize(23));}, itemCount: controller.liveChat3HostsHostIsTalkingNineModelObj.value.listrectangle46ItemList.length, itemBuilder: (context, index) {Listrectangle46ItemModel model = controller.liveChat3HostsHostIsTalkingNineModelObj.value.listrectangle46ItemList[index]; return Listrectangle46ItemWidget(model, onTapRowrectangle418: onTapRowrectangle418);})))])))); } 
onTapRowrectangle418() { Get.bottomSheet(LiveChat3HostsHostIsTalkingSevenBottomsheet(Get.put(LiveChat3HostsHostIsTalkingSevenController(),),),isScrollControlled: true,); } 
 }
