import 'controller/settings_default_one_controller.dart';import 'package:flutter/material.dart';import 'package:green_house/core/app_export.dart';import 'package:green_house/widgets/custom_button.dart';import 'package:outline_gradient_button/outline_gradient_button.dart';
// ignore_for_file: must_be_immutable
class SettingsDefaultOneDialog extends StatelessWidget {SettingsDefaultOneDialog(this.controller);

SettingsDefaultOneController controller;

@override Widget build(BuildContext context) { return Container(width: getHorizontalSize(307), padding: getPadding(all: 16), decoration: AppDecoration.fillGray90001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [Text("lbl_sign_out".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsSemiBold18), Padding(padding: getPadding(top: 13), child: Text("msg_are_you_sure_you2".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsRegular14WhiteA7001)), Padding(padding: getPadding(top: 12), child: SizedBox(width: getHorizontalSize(130), child: Divider(height: getVerticalSize(1), thickness: getVerticalSize(1), color: ColorConstant.gray90001))), Padding(padding: getPadding(top: 16), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: getPadding(right: 8), child: OutlineGradientButton(padding: EdgeInsets.only(left: getHorizontalSize(2), top: getVerticalSize(2), right: getHorizontalSize(2), bottom: getVerticalSize(2)), strokeWidth: getHorizontalSize(2), gradient: LinearGradient(begin: Alignment(0.99, 0.5), end: Alignment(0.01, 0.5), colors: [ColorConstant.yellow800, ColorConstant.green500]), corners: Corners(topLeft: Radius.circular(20), topRight: Radius.circular(20), bottomLeft: Radius.circular(20), bottomRight: Radius.circular(20)), child: CustomButton(height: getVerticalSize(40), text: "lbl_cancel".tr, margin: getMargin(right: 8), onTap: onTapCancel)))), Expanded(child: CustomButton(text: "lbl_sign_out".tr, margin: getMargin(left: 8), variant: ButtonVariant.Tertiary, fontStyle: ButtonFontStyle.PoppinsBold14))]))])); } 
onTapCancel() { Get.toNamed(AppRoutes.settingsDefaultTwoScreen); } 
 }
