import 'controller/home_two_controller.dart';import 'package:flutter/material.dart';import 'package:green_house/core/app_export.dart';import 'package:green_house/presentation/home_report_bottomsheet/home_report_bottomsheet.dart';import 'package:green_house/presentation/home_report_bottomsheet/controller/home_report_controller.dart';
// ignore_for_file: must_be_immutable
class HomeTwoBottomsheet extends StatelessWidget {HomeTwoBottomsheet(this.controller);

HomeTwoController controller;

@override Widget build(BuildContext context) { return SingleChildScrollView(child: Container(width: double.maxFinite, child: Container(width: double.maxFinite, padding: getPadding(left: 24, top: 10, right: 24, bottom: 10), decoration: AppDecoration.fillGray90001.copyWith(borderRadius: BorderRadiusStyle.customBorderTL24), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Container(height: getVerticalSize(4), width: getHorizontalSize(44), decoration: BoxDecoration(color: ColorConstant.green500, borderRadius: BorderRadius.circular(getHorizontalSize(2))))), Padding(padding: getPadding(top: 23), child: Text("lbl_share".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsMedium14WhiteA700)), Padding(padding: getPadding(top: 27), child: Text("lbl_not_interested".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsMedium14WhiteA700)), Padding(padding: getPadding(top: 28), child: Text("lbl_copy_link".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsMedium14WhiteA700)), GestureDetector(onTap: () {onTapTxtSave();}, child: Padding(padding: getPadding(top: 27, bottom: 35), child: Text("lbl_report".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsMedium14WhiteA700)))])))); } 
onTapTxtSave() { Get.bottomSheet(HomeReportBottomsheet(Get.put(HomeReportController(),),),isScrollControlled: true,); } 
 }
